### ISSUE TITLE
Default Themes

### ISSUE THREAD

**Issue by rubensrocha** [iMokhles/MultiAuthCommand#1]
Just a little suggestion: try use free/open-source themes instead to use paid themes from ThemeForest. Examples: AdminLte, CoreUi, Stisla, etc

Thanks for create this package, it's very util for us.

**Comment by iMokhles** [comment]
AdminLTE2 already supported and i'm planning to add CoreUI and Tabler, 
thanks for letting me know about Stisla ( i will add theme really soon ).
