### ISSUE TITLE
Where do we get the theme assets ?

### ISSUE THREAD

**Issue by adeyinkakoya** [iMokhles/MultiAuthCommand#2]
Where do we get the theme assets. You said to copy them to the public directory but where are the files ?

**Comment by iMokhles** [comment]
i updated the readme now with price status for each theme,

so paid admin panels comes most of times with a single **assets** folder ( inside it's HTML Demo )
so all you need to do with paid themes is creating a folder with the theme name ( lowcase or uppercase ) for example `public/startui` and put inside it the assets folder

for AdminLTE2 theme ( download latest v2 https://github.com/ColorlibHQ/AdminLTE/archive/v2.4.10.zip ) and extract the hole content inside `public/adminlte2`

for Tabler theme ( download latest dev https://github.com/tabler/tabler/archive/dev.zip ) and extract the content and place only `/dist/demo` and `/dist/assets` inside `public/tabler`

and i will try to add an option to download free themes directly to public without need a manually moves for FREE themes.

**Comment by adeyinkakoya** [comment]
Great
